 Reorder stock number      3 from vendor MYNEWCO   
   Description:  Disks, 3.5 in Floppy, 1.44 MB 
 Reorder stock number      3 from vendor MYNEWCO   
   Description:  Disks, 3.5 in Floppy, 1.44 MB 
 Reorder stock number      3 from vendor MYNEWCO   
   Description:  Disks, 3.5 in Floppy, 1.44 MB 
 Reorder stock number      3 from vendor MYNEWCO   
   Description:  Disks, 3.5 in Floppy, 1.44 MB 
